### PR TITLE
Fixes Issue #30

### PR DESCRIPTION
**Pull request by Integralist**
Changes implemented as discussed and detailed here:

https://github.com/pindexis/qfc/issues/30#issuecomment-287617729

@Naereen @nougad @michaelcontento

### CODE REVIEW

**Comment by Naereen** [comment]
Cannot test this right now, but LGTM

**Comment by Integralist** [comment]
I'm using my fork locally and it's working fine for me now

**Comment by Naereen** [comment]
Hi all, if it works, it should be merged, right?

**Comment by Integralist** [comment]
Indeed 😉 🤷‍♂️

**Comment by Naereen** [comment]
@pindexis please merge?

**Comment by pindexis** [comment]
merged. Sorry guys for the delay

**Comment by Naereen** [comment]
No problem, thanks :pray:.

**Comment by Integralist** [comment]
Awesome thanks 😀

**Pull request merged**
